TRAIN:
  ENABLE: True
  DATASET: ego4dhand
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  RANDOM_FLIP: False
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /workspace/ego4d_data_annot
  PATH_LABEL_SEPARATOR: ' '
UNIFORMERV2:
  BACKBONE: 'uniformerv2_b16'
  N_LAYERS: 8
  N_DIM: 768
  N_HEAD: 12
  MLP_FACTOR: 4.0
  BACKBONE_DROP_PATH_RATE: 0.2
  DROP_PATH_RATE: 0.4
  MLP_DROPOUT: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  CLS_DROPOUT: 0.5
  RETURN_LIST: [4, 5, 6, 7, 8, 9, 10, 11]
  DW_REDUCTION: 1.5
  NO_LMHRA: False
  DOUBLE_LMHRA: True
  TEMPORAL_DOWNSAMPLE: True
AUG:
  NUM_SAMPLE: 1
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: False
  BASE_LR: 4e-5
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 5.
  LR_POLICY: cosine
  MAX_EPOCH: 22
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 20
  ARCH: uniformerv2
  MODEL_NAME: Uniformerv2
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  USE_CHECKPOINT: False
  CHECKPOINT_NUM: [1]
TEST:
  ENABLE: False
  DATASET: ego4dhand
  BATCH_SIZE: 16
  NUM_SPATIAL_CROPS: 3
  NUM_ENSEMBLE_VIEWS: 1
  TEST_BEST: True
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: False
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

